var Global = {
    url:'http://35.224.209.5:8085/api/',
    JWT_NAME:'USER',
    ADD_USER:'ADD_USER',
    UPDT_USER:'UPDT_USER',
    DEL_USER:'DEL_USER',
    ADD_MATPRIM:'ADD_MATPRIM',
	UPDT_MATPRIM:'UPDT_MATPRIM',
	DEL_MATPRIM:'DEL_MATPRIM',
	ADD_OF:'ADD_OF',
	UPDT_OF:'UPDT_OF',
    DEL_OF:'DEL_OF',
    ADD_PRDDISP:'ADD_PRDDISP',
	UPDT_PRDDISP:'UPDT_PRDDISP',
	DEL_PRDDISP:'DEL_PRDDISP',
    HTTP_OK:200,
    OK:'OK',
    ERROR:'ERROR',
    OPEN:'OPEN',
    DRAFT:'DRAFT',
    TEP:'TEP',
    WTDEL:'WTDEL',
    CMPLT:'CMPLT',
    DELVRD:'DELVRD',
    SIZE_DOC:8
};

export default Global