var Global = {
    //url:'https://localhost:8443/api/',
    //url:'http://ready2solve.club:8085/api/',
    url:'http://localhost:8085/api/',
    JWT_NAME:'USER',
    ADD_USER:'ADD_USER',
    UPDT_USER:'UPDT_USER',
    DEL_USER:'DEL_USER',
    ADD_MATPRIM:'ADD_MATPRIM',
	UPDT_MATPRIM:'UPDT_MATPRIM',
	DEL_MATPRIM:'DEL_MATPRIM',
	ADD_OF:'ADD_OF',
	UPDT_OF:'UPDT_OF',
    DEL_OF:'DEL_OF',
    ADD_PRDDISP:'ADD_PRDDISP',
	UPDT_PRDDISP:'UPDT_PRDDISP',
	DEL_PRDDISP:'DEL_PRDDISP',
    HTTP_OK:200,
    OK:'OK',
    ERROR:'ERROR',
    OPEN:'OPEN',
    APRVD:'APRVD',
    DRAFT:'DRAFT',
    TEP:'TEP',
    WTDEL:'WTDEL',
    CMPLT:'CMPLT',
    DELVRD:'DELVRD',
    EEP:'EEP',
    SIZE_DOC:8,
    PORCENTAJE_MAX:'100.00',
    CODIGO_AGUA:'AGUA001'
};

export default Global